name: php-course

networks:
  course-network:
    driver: bridge

services:
  leilao-api:
    build:
      context: ./leilao-api
      dockerfile: Dockerfile
    volumes:
      - ./leilao-api/src:/usr/src/app/src
      - ./leilao-api/tests:/usr/src/app/tests
      - ./leilao-api/composer.json:/usr/src/app/composer.json
      - ./leilao-api/composer.lock:/usr/src/app/composer.lock
    networks:
      - course-network
